alias vim="nvim"
alias gcane="git commit -a --amend --no-edit"
alias bubucop="bundle exec rubocop -A"
alias gb="git branch --sort=-committerdate"
alias rg="rg --ignore-file ${HOME}/.rgignore"

export TERM=screen-256color
# cloudplatform: add Shopify clusters to your local kubernetes config
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
# load dev, but only if present and the shell is interactive
if [[ -f /opt/dev/dev.sh ]] && [[ $- == *i* ]]; then
  source /opt/dev/dev.sh
fi
